#!/bin/sh
sudo_user=`basename $HOME`
USER_WRAPPER="sudo -u $sudo_user"

if $USER_WRAPPER /bin/launchctl list "org.keyboxwallet.daemon" &> /dev/null; then
   $USER_WRAPPER /bin/launchctl unload /Library/LaunchAgents/org.keyboxwallet.daemon.plist
fi
